In [125]:
#Run this block first to change names of csv files
ANS_df = 'ans_test - Form responses 1.csv'
memory_df = 'memory_test - Form Responses 1.csv'
maths_df = 'maths_test - Form Responses 1.csv'

In [139]:
import pandas as pd
from scipy import stats
from scipy.stats import sem
import numpy as np 

#Creating new dataframes for the different genders
def gender(csv_file):
    df = pd.read_csv(csv_file) 
    male_df = df[df.gender == 'm']
    female_df = df[df.gender == 'f'] 
    others_df = df[df.gender == 'o'] 
    
    #calculating mean for total scores of each gender 
    m_mean = male_df['score'].mean()
    f_mean = female_df['score'].mean()


    #Calculating variances of total scores of each gender 
    m_var = np.var(male_df['score'])
    f_var = np.var(female_df['score'])

    #Calculating t test 
    t_statistic, p_value = stats.ttest_ind(male_df['score'], female_df['score'], equal_var = False) 

    #Calculating standard error of mean 
    m_SE = sem(male_df['score']) 
    f_SE = sem(female_df['score']) 

    #Creating a dictionary for the calculated values 
    data_table = {
    '': {'male mean':m_mean,'male SE': m_SE, 'female mean':f_mean, 'female SE':f_SE,
             'score difference':abs(m_mean-f_mean), 'p-value' :p_value}
    }

    #Converting dictionary into PANDAS dataframe
    df_table = pd.DataFrame(data=data_table)
    
    return df_table

#Repeating function with different tests, then transposing table to correct format
ANS_stats = gender(ANS_df).transpose()
memory_stats = gender(memory_df).transpose()
maths_stats = gender(maths_df).transpose()

#Merging all dataframes using pd.concat()
new_stats = pd.concat([ANS_stats, memory_stats, maths_stats], keys=['ANS test','Memory test', 'Maths test'])

#Final summary table with all values 
new_stats

,,male mean,male SE,female mean,female SE,score difference,p-value
ANS test,,28.600000,0.600000,28.555556,0.572931,0.044444,0.957741
Memory test,,6.307692,0.644350,6.809524,0.592087,0.501832,0.570808
Maths test,,18.461538,1.394198,17.428571,1.135093,1.032967,0.570479

In [89]:
# calculate the spearman's correlation between two variables
from numpy.random import rand
from numpy.random import seed
from scipy.stats import spearmanr

#Defining spearman function from CSV files
def spearmanfunc(csv_file1, csv_file2):
    df1 = pd.read_csv(csv_file1) 
    df2 = pd.read_csv(csv_file2) 
    percentage_df1 = df1['percentage_score'].to_numpy()
    percentage_df2 = df2['percentage_score'].to_numpy()
    coef, p = spearmanr(percentage_df1, percentage_df2)
    return coef, p


ANS_memory_coef, ANS_memory_p = spearmanfunc('ANS.csv', 'memory.csv')
ANS_maths_coef, ANS_maths_p = spearmanfunc('ANS.csv', 'maths.csv') 

#Creating a dictionary for results
d_table = {
    'Memory test' : {'Coefficient': ANS_memory_coef, 'p value': ANS_memory_p}, 
    'Maths test' : {'Coefficient': ANS_maths_coef, 'p value': ANS_maths_p}, 

} 

df = pd.DataFrame(data=d_table)
df1 = df.transpose()
df1

             Coefficient   p value
Memory test     0.220826  0.209469
Maths test      0.035611  0.841526